on:
  push:
    paths:
      - '**.Rmd'
      - '.github/workflows/*'
  workflow_dispatch:
  schedule:
      - cron: '00 9 * * *'
  repository_dispatch:
    types: ['status-update']

name: Render Status

jobs:
  render:
    name: Render Status
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::devtools
            any::rmarkdown
            any::rcmdcheck
            any::gh
            any::purrr
            any::dplyr
            any::tidyr
            any::glue
            any::readr
            any::knitr
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
      - name: Execute Script
        run: |
          Rscript "data-raw/update.R"
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit --all -m "[status] $(date +'%F %T %Z')" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
